views.filter.views_range_filter_sapi_date:
  type: views.filter.search_api
  label: 'Search API Date Range Filter'
  mapping:
    value:
      type: mapping
      label: 'Filter values'
      mapping:
        min:
          type: string
          label: 'From value'
        max:
          type: string
          label: 'To value'
        type:
          type: string
          label: 'Value type (date or offset)'
    start_field:
      type: string
      label: 'Start field'
    end_field:
      type: string
      label: 'End field'
    from_label:
      type: label
      label: '"From" label'
    to_label:
      type: label
      label: '"To" label'
    single_bound_behaviour:
      type: string
      label: 'Record NULL field behaviour (open, equal, exclude)'
    missing_bounds_behaviour:
      type: string
      label: 'Record both-NULL behaviour (include, exclude)'

views.filter.views_range_filter_sapi_int:
  type: views.filter.search_api
  label: 'Search API Numeric Range Filter'
  mapping:
    value:
      type: mapping
      label: 'Filter values'
      mapping:
        min:
          type: string
          label: 'From value'
        max:
          type: string
          label: 'To value'
        type:
          type: string
          label: 'Value type'
    start_field:
      type: string
      label: 'Start field'
    end_field:
      type: string
      label: 'End field'
    from_label:
      type: label
      label: '"From" label'
    to_label:
      type: label
      label: '"To" label'
    single_bound_behaviour:
      type: string
      label: 'Record NULL field behaviour (open, equal, exclude)'
    missing_bounds_behaviour:
      type: string
      label: 'Record both-NULL behaviour (include, exclude)'

views.filter.views_range_filter_sql_date:
  type: views_filter
  label: 'SQL Date Range Filter'
  mapping:
    value:
      type: mapping
      label: 'Filter values'
      mapping:
        min:
          type: string
          label: 'From value'
        max:
          type: string
          label: 'To value'
        type:
          type: string
          label: 'Value type (date or offset)'
    start_field:
      type: string
      label: 'Start field'
    end_field:
      type: string
      label: 'End field'
    from_label:
      type: label
      label: '"From" label'
    to_label:
      type: label
      label: '"To" label'
    single_bound_behaviour:
      type: string
      label: 'Record NULL field behaviour (open, equal, exclude)'
    missing_bounds_behaviour:
      type: string
      label: 'Record both-NULL behaviour (include, exclude)'

views.filter.views_range_filter_sql_int:
  type: views_filter
  label: 'SQL Numeric Range Filter'
  mapping:
    value:
      type: mapping
      label: 'Filter values'
      mapping:
        min:
          type: string
          label: 'From value'
        max:
          type: string
          label: 'To value'
        type:
          type: string
          label: 'Value type'
    start_field:
      type: string
      label: 'Start field'
    end_field:
      type: string
      label: 'End field'
    from_label:
      type: label
      label: '"From" label'
    to_label:
      type: label
      label: '"To" label'
    single_bound_behaviour:
      type: string
      label: 'Record NULL field behaviour (open, equal, exclude)'
    missing_bounds_behaviour:
      type: string
      label: 'Record both-NULL behaviour (include, exclude)'
